version: '3'

services:
    codebert:
        container_name: facos
        build: .
        # runtime: nvidia
        deploy:
            resources:
              reservations:
                devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        ports:
            - "9191:9191"
        volumes:
            - ./:/app/facos
        tty: true


